apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-test-app-psp
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/pardhap18/flux-test-app-psp
  ref:
    branch: main
  secretRef:
    name: flux-test-app-psp-secret
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    